const validPrefixes=["0811","0812","0813","0821","0822","0851","0852","0853","0896","0897","0898","0899","0831","0832","0833","0855","0856","0877","0878","0881","0882","0883","0884","0885","0886","0887","0888","0889"];function validateWhatsApp(){let e=document.getElementById("whatsapp"),t=e.value.trim();if(e.setCustomValidity(""),t.startsWith("0")){if(t.length<10)e.setCustomValidity("Nomor WhatsApp harus memiliki minimal 12 digit.");else{let a=t.substring(0,4);validPrefixes.includes(a)||e.setCustomValidity("Nomor yang kamu masukkan salah atau tidak terdaftar.")}}else e.setCustomValidity("Nomor WhatsApp harus dimulai dengan angka 0.")}document.getElementById("rsvpForm").addEventListener("submit",function(e){e.preventDefault();let t=document.getElementById("rsvpForm"),a=t.querySelector("#whatsapp"),i=a.value.trim(),s=t.querySelector('button[type="submit"]'),l=s.querySelector(".spinner"),n=document.getElementById("notification");if(!i.startsWith("0")){a.setCustomValidity("Nomor WhatsApp harus dimulai dengan angka 0.");return}if(i.length<10){a.setCustomValidity("Nomor WhatsApp harus memiliki minimal 12 digit.");return}let r=i.substring(0,4);if(!validPrefixes.includes(r)){a.setCustomValidity("Nomor yang kamu masukkan salah atau tidak terdaftar.");return}s.querySelector("span").style.display="none",l.style.display="inline-block";let o=new FormData(t),d=new Date,m=d.toLocaleString("id-ID",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:!1}).replace(",","");o.append("timestamp",m),o.append("status","Belum Terkirim"),fetch("https://script.google.com/macros/s/AKfycbxsTsi3WR22ZF_U7XDcxREcrgQ2Qa9HCQiGco4a9KhqB542EX6LbkD-ycPDC0QDqOzPdQ/exec",{method:"POST",body:o}).then(e=>e.text()).then(()=>{n.textContent="Terkirim!",n.style.display="block",t.reset(),setTimeout(()=>{n.style.display="none"},3e3),l.style.display="none",s.querySelector("span").style.display="inline-block";let e=document.createElement("div");e.className="comment-item";let a=o.get("name"),i=o.get("attending"),r=o.get("message");e.innerHTML=`
	  <div class="d-flex">
	  <img src="https://ui-avatars.com/api/?size=40&amp;background=random&amp;color=random&amp;name=${a}" alt="${a}" class="avatar rounded-circle" style="height: 30px; width: 30px;"/>
	  <div class="ml-2 text-left">
      <p class="mb-0 font-weight-bold">${a}<span class="badge alert-info ${"Hadir"===i?"hadir":"Tidak Hadir"===i?"tidak-hadir":""}">${i}</span></p>
      <p class="mb-0 pesan">${r}</p>
      <small>${m}</small> <!-- Menambahkan waktu ke tampilan -->
	  </div>
      </div>
    `;let d=document.getElementById("rsvpDisplayContainer");d.prepend(e),history.replaceState(null,document.title,window.location.pathname)}).catch(e=>{console.error("Error:",e),alert("Terjadi kesalahan. Silakan coba lagi."),l.style.display="none",s.querySelector("span").style.display="inline-block"})});let start=0;const limit=4;let isLoading=!1,allDataLoaded=!1;function toggleLoadingMessage(e){let t=document.getElementById("loadingMessage");e?t.style.display="block":t.style.display="none"}async function loadData(){if(isLoading||allDataLoaded)return;isLoading=!0,toggleLoadingMessage(!0);let e=`https://script.google.com/macros/s/AKfycbxsTsi3WR22ZF_U7XDcxREcrgQ2Qa9HCQiGco4a9KhqB542EX6LbkD-ycPDC0QDqOzPdQ/exec?start=${start}&limit=4`;try{let t=await fetch(e),a=await t.json(),i=document.getElementById("rsvpDisplayContainer");if(a.length>0){a.forEach(e=>{let t="Hadir"===e.attending?"hadir":"Tidak Hadir"===e.attending?"tidak-hadir":"",a=document.createElement("div");a.className="comment-item",a.innerHTML=`
		  <div class="d-flex">
		  <img src="https://ui-avatars.com/api/?size=40&amp;background=random&amp;color=random&amp;name=${e.name}" alt="${e.name}" class="avatar rounded-circle" style="height: 30px; width: 30px;"/>
		  <div class="ml-2 text-left">
          <p class="mb-0 font-weight-bold">${e.name}<span class="badge alert-info ${t}">${e.attending}</span></p>
          <p class="mb-0 pesan">${e.message}</p>
          <small>${e.timestamp}</small>
    	  </div>
    	  </div>
        `,i.appendChild(a)}),start+=4;let s=document.getElementById("noMoreDataMessage");s&&s.remove()}else if(!document.getElementById("noMoreDataMessage")){let l=document.createElement("div");l.id="noMoreDataMessage",l.textContent="Semua komentar telah dimuat.",l.style.textAlign="center",l.style.fontSize="12px",l.style.color="#777",i.appendChild(l),allDataLoaded=!0,setTimeout(()=>{l.remove()},5e3)}}catch(n){console.error("Error fetching data:",n)}finally{isLoading=!1,toggleLoadingMessage(!1)}}function observeLastItem(){let e=document.getElementById("rsvpDisplayContainer"),t=e.lastElementChild;if(t){let a=new IntersectionObserver(e=>{e.forEach(e=>{e.isIntersecting&&(console.log("Elemen terakhir terlihat, memuat data..."),loadData())})},{root:null,rootMargin:"0px",threshold:1});a.observe(t)}}window.addEventListener("DOMContentLoaded",loadData);const container=document.getElementById("rsvpDisplayContainer"),mutationObserver=new MutationObserver(()=>{observeLastItem()});mutationObserver.observe(container,{childList:!0,subtree:!0}),observeLastItem();